In [1]:
import pandas as pd
import openai

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

Read the sampled dataset with Amazon Inventory Data

In [2]:
df_items = pd.read_json("../../../data/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [3]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,AMAZON FASHION,"Bosttor Bluetooth Beanie Hat with Light, Headl...",4.5,2342,"[100% Acrylic, Elastic closure, Hand Wash Only...",[],26.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Beanie Hat with Bluetooth Headphon...,Bosttor,"[Electronics, Headphones, Earbuds & Accessorie...","{'Department': 'unisex-adult', 'Date First Ava...",B0BH41HYFZ,NaN,NaN,NaN
1,All Electronics,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",4.2,148,[【USB or USB C to Ethernet Adapter】The Etherne...,[],14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aceele,"[Electronics, Computers & Accessories, Network...",{'Product Dimensions': '3.54 x 0.98 x 0.71 inc...,B0BKPB2YQ9,NaN,NaN,NaN
2,All Electronics,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,4.2,3331,[📍3-Port HDMI Switch: This aluminum HDMI switc...,[],18.98,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Darren reviews VWRHAR 3-1 splitter...,VWRHar,"[Electronics, Home Audio, Home Audio Accessori...",{'Package Dimensions': '6.1 x 4.21 x 0.94 inch...,B09MM5QT3R,NaN,NaN,NaN
3,All Electronics,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",3.4,125,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Burxoe,[],{'Package Dimensions': '3.15 x 3.07 x 2.52 inc...,B09Q5TNDHY,NaN,NaN,NaN
4,Cell Phones & Accessories,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",4.7,335,[【Compatible Airpods 1/2 】This case designed f...,[1],11.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'airpod cases', 'url': 'https://www...",UGUHY,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '7.44 x 4.61 x 1.57 inc...,B0BZJKX7MS,NaN,NaN,NaN

In [4]:
list(df_items["features"].items())[0]

(0,
 ['100% Acrylic',
  'Elastic closure',
  'Hand Wash Only',
  '【Upgraded Bluetooth Beanie】Bosttor upgraded Bluetooth wireless technology offer much stable and strong connection, support music and calling, easy and fast to pair with your devices. Maximum transmission distance up to 33 feet. Built-in Stereo Speakers & Mic, enhance your music listening experience.',
  '【Long Working Time Music Hat】Built with easy-access USB charging port, simply charge it via the included USD cable. It takes 1-2 hours to get full charged. The battery offers continuous working hours up to 10 hours. Perfect for camping, hiking, skiing, hunting, jogging, cycling, dog walking, auto repair, etc.',
  '【LED Headlight Light Up Your Way】Hands-free LED light is rechargeable and removable. You can remove it to charge by laptop, power bank, socket, car charger, etc. The 4 LED lights can light up to 30 feet away. It points directional light toward what your eyes are looking at. It has 3 brightness settings.',
  '【One Size Fits Most】Bosttor unisex beanie hat is made from the ultra-soft acrylic blend material that provides excellent insulation against cold winter air. Elastic and comfortable LED hat fits men women and teens. It is hand washable, please remove the LED and the headset before washing.',
  '【Ideal Birthday & Christmas Gifts】Our beanie hat with Bluetooth and LED headlight is the ideal gift for runners and outdoor adventurers in winter. It is also your best gift choice for men women and teenagers. This is the perfect gift for anyone in the family and your friends. Your Ideal choice for Thanksgiving Day, Christmas, Birthday and Anniversary.'])

In [5]:
list(df_items["images"].items())[0]

(0,
 [{'thumb': 'https://m.media-amazon.com/images/I/51b7qcj8dZL._AC_SR38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51b7qcj8dZL._AC_.jpg',
   'variant': 'MAIN',
   'hi_res': 'https://m.media-amazon.com/images/I/71G+JK9lg1L._AC_UL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51JvxXFcBwL._AC_SR38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51JvxXFcBwL._AC_.jpg',
   'variant': 'PT01',
   'hi_res': 'https://m.media-amazon.com/images/I/71vYog2F1LL._AC_UL1300_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51sKkBrOCiL._AC_SR38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51sKkBrOCiL._AC_.jpg',
   'variant': 'PT02',
   'hi_res': 'https://m.media-amazon.com/images/I/71GowojGFfL._AC_UL1300_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51k6uDxkZpL._AC_SR38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51k6uDxkZpL._AC_.jpg',
   'variant': 'PT03',
   'hi_res': 'https://m.media-amazon.com/images/I/71ODAwqvoWL._AC_UL1300_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51iGNUuEBTL._AC_SR38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51iGNUuEBTL._AC_.jpg',
   'variant': 'PT04',
   'hi_res': 'https://m.media-amazon.com/images/I/71JT2rmTQuL._AC_UL1300_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51fLdANve5L._AC_SR38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51fLdANve5L._AC_.jpg',
   'variant': 'PT05',
   'hi_res': 'https://m.media-amazon.com/images/I/71Ho2OMTqQL._AC_UL1300_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/61h2Baw2C2L._AC_SR38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/61h2Baw2C2L._AC_.jpg',
   'variant': 'PT06',
   'hi_res': 'https://m.media-amazon.com/images/I/81d4-6PK0ML._AC_UL1300_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51C3h3Rp8WL._AC_SR38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51C3h3Rp8WL._AC_.jpg',
   'variant': 'PT07',
   'hi_res': 'https://m.media-amazon.com/images/I/61pk9V7MQXL._AC_UL1300_.jpg'}])

Preprocessing Functions

In [6]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [7]:
def extract_first_large_image(row):
    return row["images"][0].get("large", "")

In [8]:
df_items["preprocessed_description"] = df_items.apply(preprocess_description, axis=1)
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [9]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,preprocessed_description,image
0,AMAZON FASHION,"Bosttor Bluetooth Beanie Hat with Light, Headl...",4.5,2342,"[100% Acrylic, Elastic closure, Hand Wash Only...",[],26.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Beanie Hat with Bluetooth Headphon...,Bosttor,"[Electronics, Headphones, Earbuds & Accessorie...","{'Department': 'unisex-adult', 'Date First Ava...",B0BH41HYFZ,NaN,NaN,NaN,"Bosttor Bluetooth Beanie Hat with Light, Headl...",https://m.media-amazon.com/images/I/51b7qcj8dZ...
1,All Electronics,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",4.2,148,[【USB or USB C to Ethernet Adapter】The Etherne...,[],14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aceele,"[Electronics, Computers & Accessories, Network...",{'Product Dimensions': '3.54 x 0.98 x 0.71 inc...,B0BKPB2YQ9,NaN,NaN,NaN,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",https://m.media-amazon.com/images/I/41WsGRr-3T...
2,All Electronics,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,4.2,3331,[📍3-Port HDMI Switch: This aluminum HDMI switc...,[],18.98,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Darren reviews VWRHAR 3-1 splitter...,VWRHar,"[Electronics, Home Audio, Home Audio Accessori...",{'Package Dimensions': '6.1 x 4.21 x 0.94 inch...,B09MM5QT3R,NaN,NaN,NaN,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,https://m.media-amazon.com/images/I/41fsjaknf1...
3,All Electronics,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",3.4,125,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Burxoe,[],{'Package Dimensions': '3.15 x 3.07 x 2.52 inc...,B09Q5TNDHY,NaN,NaN,NaN,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",https://m.media-amazon.com/images/I/51YFypeuZh...
4,Cell Phones & Accessories,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",4.7,335,[【Compatible Airpods 1/2 】This case designed f...,[1],11.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'airpod cases', 'url': 'https://www...",UGUHY,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '7.44 x 4.61 x 1.57 inc...,B0BZJKX7MS,NaN,NaN,NaN,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",https://m.media-amazon.com/images/I/41V7Wi2ckb...

Sample 50 items from dataset

In [10]:
df_sample = df_items.sample(n=50, random_state=42)

In [11]:
len(df_sample)

50

In [12]:
df_data_to_embed = df_sample[["preprocessed_description", "image", "rating_number", "price", "average_rating", "parent_asin"]]

In [13]:
df_data_to_embed.head()

,preprocessed_description,image,rating_number,price,average_rating,parent_asin
521,Marame 120mm 5v USB Powered Fan with Speed Con...,https://m.media-amazon.com/images/I/41Zpg4vSEj...,104,14.99,4.7,B0BRJS644Z
737,"Kids Wireless Headphones, Adjustable Headband,...",https://m.media-amazon.com/images/I/41+jaEbUbY...,173,NaN,4.2,B09KQP2H7N
740,"Veetone Aux Cord for iPhone, 3.3ft [Apple MFi ...",https://m.media-amazon.com/images/I/31ag2Blvjm...,2218,5.99,4.0,B0CC4HBS85
660,AICHESON Laptop Cooler Pad with 6 Cooling Fans...,https://m.media-amazon.com/images/I/51BKtk3-RD...,145,NaN,4.2,B099N9F3FP
411,"Raymate Bluetooth Speakers, HiFi Stereo Sound ...",https://m.media-amazon.com/images/I/31SnPdXS77...,270,38.69,4.7,B0C996WY16

In [14]:
data_to_embed = df_data_to_embed.to_dict(orient="records")

In [15]:
data_to_embed

[{'preprocessed_description': 'Marame 120mm 5v USB Powered Fan with Speed Controller Cooling for Router Modem Receiver DVR Xbox TV Box (120mm x 120mm x 55mm) 【Solve Your Cooling Problem】\xa0This fan will do the job keeping your devices from overheating and keep your electronics running cool. You can also use them in confined spaces for cooling various electronics. blowing cool air through it to aid in longevity. 【Speed\xa0Control\xa0Switch】 The speed controller located on the cord allows you to adjust the fan’s speed from off to low, medium, and high. This enables you to set the fan to optimal noise and airflow levels for various environments. 【High Compatibility USB-Powered】 Powered by a 3.3ft USB cable. Compatible with desktop, laptop, power bank, AC adapters, car chargers, and other power supplies that support USB connection. USB fan is energy-saving and environmentally friendly. 【Rubber Feet & Dust Filter】\xa0Rubber Feet on the fan raise it up enough off of the surface it is sitting on to allow enough replacement air to be drawn in, under the suction side of the fan. rubber feet with non-slip pads to keep this fan from sliding and absorbs any vibration noise.\xa0Dust Filter on the fan both sides. does not blow dirt or dust onto your devices. 【Widely Applications】It is works great to cool an airflow-restricted entertainment center. such as cooling for Router TV Box\xa0\xa0Modem X-box Audio Receiver Cabinet Stereo Amplifier.',
  'image': 'https://m.media-amazon.com/images/I/41Zpg4vSEjL.jpg',
  'rating_number': 104,
  'price': 14.99,
  'average_rating': 4.7,
  'parent_asin': 'B0BRJS644Z'},
 {'preprocessed_description': "Kids Wireless Headphones, Adjustable Headband, Stereo Sound, 3.5mm Jack, Kids Bluetooth Headphones, Volume Control, Foldable, Build-in Microphone, Over-Ear Headphones for Kids for School Home, Yellow 【WIRELESS & WIRED KIDS HEADPHONES】 Stunning kid headphones, built with the latest high quality 5.0 Bluetooth chip, which allows kids wireless headphones to connect fast and stable, also with 3.5mm jack to connect any device. You can use them as wireless headphones and wired headphones, compatible with smartphones, laptops, tablets, computers, TVs and many other Bluetooth-enabled devices, making it possible to provide you with great music anywhere in the occasion. 【Cute cat headphones】It is designed with cute cartoon pattern, you can use it in any venue. Our over-ear headphones provide you with easy to control high quality sound, comfortable and soft ear cushions can protect your child's ears well, it is a beautiful birthday or Christmas gift for girls, children, teenagers, adult women. 【Excellent sound quality and adjustable headband】 This baby headphones is designed for children, no need to worry about the damage caused by rough handling. Stretchable, foldable design is convenient for travel and storage. Clear stereo sound quality provides you with the best listening enjoyment, full sound, supports connection to Bluetooth, 3.5mm headphone jack, SD card, connect and enjoy all the favorite content for boys and girls. 【Long battery life and built-in microphone】Our toddler headphones have a battery capacity of up to 400mAh and last up to 7 hours, so even when the battery runs out, you can still use it through the audio hole. Built-in microphone for taking calls, video chats, or online lessons. Perfect for: kids headphones for school, outdoor headphones for boys and girls Yellow cartoon headphones 【100% satisfaction after-sales service】 Our brand always puts customers first, if you have any problems with your headphones, please feel free to contact us through seller support, we will provide you with attentive customer service within 24 hours.",
  'image': 'https://m.media-amazon.com/images/I/41+jaEbUbYL._AC_.jpg',
  'rating_number': 173,
  'price': nan,
  'average_rating': 4.2,
  'parent_asin': 'B09KQP2H7N'},
 {'preprocessed_description': 'Veetone Aux Cord for iPhone, 3.3ft [Apple MFi Certified] Lightning to 3.5mm AUX Audio Cable Compatible with iPhone 14 13 12 11 XS XR X 8 7 6 for Home Car Stereo/Headphone/Speaker, Support All iOS 【2023 Newest Version】 Newest Apple MFi chips make this aux cord for car can support all iOS version and compatible with iPhone 14/14 Pro/14 Pro Max/14 Plus/13/13 Pro/13 Pro Max/13 Mini/12/12 Pro/12 Pro Max/12 Mini/11/11 Pro/Xs/XS Max/X/8/8 Plus/7/7 Plus and more. Easily play audio from your iPhone on car stereo, headphone, Hi-Fi, speaker with 3.5mm aux ports or other 3.5mm-compatible audio output devices. 【Plug and Play】 No need any driver or adapter, enjoy high quality music instantly. Ultra-thin extensions of the connector enable fit with most of phone case, No need to remove cases for more convenient use. The aux to lightning cable allows you to enjoy high-quality music anytime and anywhere. 【Enjoy Hi-Fi Music】 This aux cord for iPhone car adapter was built-in newest powerful DAC chip and premium copper wires to ensures stable and lossless sound transmission of audio signal, provide flawlessly music transmission and clear Hi-Fi sound quality. You can enjoy high quality music via connecting your iPhone to your car or home stereo, headphones, Hi-Fi, computer stereo etc. 【Ultra Durability】 The lightning to 3.5 mm audio cable is made of high-quality polished metal connector, gold-plated 3.5mm conductor and durable stretch plastic wire material, fast and sturdy connection, protect it from breaking, 100% durable to use.The auxiliary line is 1 meters long, which can be a better use when you are listening to music in the car. 【Powerful Functions】 The iPhone aux cord for car enables you to play audio on your car stereo, headphone, Hi-Fi, computer stereo, bluetooth speaker with 3.5mm aux ports or other 3.5mm compatible output devices. Great for home & travel. This aux cord for iPhone 13 14 is a good choice as a gift for your family or friends.',
  'image': 'https://m.media-amazon.com/images/I/31ag2BlvjmL.jpg',
  'rating_number': 2218,
  'price': 5.99,
  'average_rating': 4.0,
  'parent_asin': 'B0CC4HBS85'},
 {'preprocessed_description': 'AICHESON Laptop Cooler Pad with 6 Cooling Fans for 11" - 15.6" Laptops, RED Lights Super Laptop Cooling Fans - AICHESON cooling pads laptop is specially designed with 6 (70mm) cooling fans, each fan speed is 1500-2200RPM from level 1 to level 6, providing you adjustable airflows to lengthen the life of your laptop Ergonomic Heights Stands - Once the hook is dropped, it is locked in position, and it is very convenient to adjust the angles and heights, angles can change from 10 to 27 degrees, raising your laptop up 2.83" to 5.19", providing you a better and a more comfortable posture when using the laptop Low Noise and Easy Operation - Even structured with 6 cooling fans, the noise level is 25dBA - 28 dBA, which is just like someone whispers around your ear. And the LCD display control panel allows you to adjust fan speed easily. There is no need to wrap your hands behind the cooler to operate, which is very troublesome 3 Modes and Extra USB Ports - Long pressing the ON/OFF button to adjust modes from 1, 2, 3, it\'s free to choose according to the situation. Extra USB ports allow you to connect a mouse, a keyboard. 2 small hidden anti-slip pads are helpful to protect your laptop, please remember to open them Widely Compatibility - The laptop fan cooling pad is compatible with all laptops from 13" to 15.6", and weighs 1.6LB, measures 14.56" x 10.43" x 1.26", portable for you to carry with your laptop.',
  'image': 'https://m.media-amazon.com/images/I/51BKtk3-RDL._AC_.jpg',
  'rating_number': 145,
  'price': nan,
  'average_rating': 4.2,
  'parent_asin': 'B099N9F3FP'},
 {'preprocessed_description': 'Raymate Bluetooth Speakers, HiFi Stereo Sound with DSP, 30W IPX7 Waterproof Speaker Wireless Bluetooth-V5.0, 1000mins Playtime, Portable Speaker for Home, Outdoor, Party 🎶HiFi Sound: With proven audio processing DSP chip technology, 30W dual speaker drivers and a more powerful amplifier module, the portable speakers delivers even, Balanced Sound Without Distortion. 🧱Integrated structure: With IPX7 Waterproof Speakers protection against rain, dust, snow and splashes, you can enjoy music in the pool, beach, park, bathroom and beyond.Comes with a dirt and corrosion resistant portable silicone protective sleeve. ✨Simple And Stylish: This is a speaker with a golden ratio rectangular body, combined with the purest colors, perfect for a variety of venues. 🔋Extended Battery Life: 3600mAh high-capacity battery provides you with more than 1000mins of play time.This speaker uses a more stable charging port - type C port, which greatly saves your waiting time. Note: We provide a 180 day warranty service and a 24-hour customer service response service.',
  'image': 'https://m.media-amazon.com/images/I/31SnPdXS77L._AC_.jpg',
  'rating_number': 270,
  'price': 38.69,
  'average_rating': 4.7,
  'parent_asin': 'B0C996WY16'},
 {'preprocessed_description': "iPhone Charger Cord [Apple MFi Certified] Lightning Cable 1m/3.3FT Fast Charging High Speed Data Sync USB Cable Compatible with iPhone 14/13/12/11 Pro Max/XS MAX/XR/XS/X/8/7/Plus/6S iPad [Fast Charging & Sync] - iPhone Charger Cord Max 2.4 output current, high quality copper wire, improve charging and data transfer speed of iPhone charging cable. iPhone Lightning Cable ensures faster charging time and keeps your device safer. [Perfect comptibility] - iPhone lightning cables compatible with iPhone 14/14 Plus/14 Pro/14 Pro Max/iPhone 13/13 mini/13 Pro/13 Pro Max/12/12 mini/12 Pro/12 Pro Max/11/11 Pro/11 Pro Max/SE 2/XS/XS Max/XR/X/8Plus/8/7Plus/7/6s Plus/6s/6 Plus/6/5s/5c,iPad,AirPods [MFi Certified] - The lightning cable has an original lightning chip inside. Make sure it's compatible with your iPhone and charges your device safely. Enjoy fast data transfer, sync and charging. [Superior Durability] - iPhone lightning cable are made of top quality materials and coated with premium TPE. Passed 10,000 flex tests and won't get tangled for extra protection and durability. [What you get?] - 1x 3ft Mfi Certified iPhone Charging Cable. If you have any quality problems with our products, please feel free to contact us. We provide 24/7 customer support",
  'image': 'https://m.media-amazon.com/images/I/31CSP4L973L.jpg',
  'rating_number': 119,
  'price': 4.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BN1CMWCP'},
 {'preprocessed_description': 'Skovlys Avocado Stickers for Water Bottles,Vinyl Waterproof Stickers for Water Bottle,50 Pcs Waterproof Vinyl Stickers for Water Bottle, Laptop, Phone Case, Guitaromputer,Phone,Guitar 🥑Avocado Stickers Pack,50pcs each pack, 50pcs no-duplicate stickers,2.5-3.5 inch each pcs 🥑3-layer structure, the surface layer is made of waterproof and scratch-resistant material, the printing layer is made of UV 7-color printing with bright colors, and the primer is made of PVC non-marking removable glue 🥑Our assortment of graffiti decals is your best choice when choosing a gift for your friends, kids. These creative patches will be the perfect present to make a cool room or for DIY decoration 🥑Stick them and use them for your Laptops, Skateboards, Luggage, Cars, Bikes, Bicycles, Bedroom, Travel Case, Bicycle, Motorcycle, Snowboard, PS4, XBOX ONE, etc.Guitar 🥑We are 100% guaranteed that you are completely satisfied with your product or receive your refund. We Partnered with Amazon FBA to give you the highest quality Amazon Prime shipping and hassle free returns.',
  'image': 'https://m.media-amazon.com/images/I/618pgbbaFnL._AC_.jpg',
  'rating_number': 128,
  'price': 5.99,
  'average_rating': 4.8,
  'parent_asin': 'B0B5CYWHWV'},
 {'preprocessed_description': '12 13 13.3 14 15.4 15.6 Inches Laptop Skin Sticker Decal Universal Netbook Skin Sticker | Need to Cut,Easy to Apply, Remove and Change Styles (Morning Glory) 100% Brand New and High Quality. Our laptop skins 15.6 inch，laptop skins 15.6 inch Fits up to 12.1"-15.6" laptops.High Resolution Printing. Flexible Film Helps Protect the Laptop Surface From Scratches & Smudges. We\'ve Made The Best Laptop Skin Sticker Decal Available and in a Variety of Wonderful Colors,PVC_Removable Layer & Paper layer; Three films aret of Our Way to Make Sure You are 100% Satisfied. Easy to Remove and Reuse .Will Last For Years and Won\'t Fade, Three Films are Included,one For the Back Side of The LCD Screen and Two For the Sides of the Touch Pad. About 38.0cm(15.0 inch) x 27.0cm( 10.6 inch);Compatible with :Most 12" ~ 15.6" wide Screen Notebook. The Sticker is Only One Size,You Maybe Need to Cut by Yourself to Fit Your Laptop. This is a No-Risk Purchase.If you have any questions for it ,No Hassle Refund Guaranteed.It can be a Sweet Gift Idea for Your Loved ones. We Will Go Out of Our Way to Make Sure You are 100% Satisfied.',
  'image': 'https://m.media-amazon.com/images/I/51VLMlQuP4L._AC_.jpg',
  'rating_number': 102,
  'price': 9.99,
  'average_rating': 4.1,
  'parent_asin': 'B09WCT9S1R'},
 {'preprocessed_description': 'Geiomoo Silicone Case Compatible with Anker Soundcore Sport X10, Protective Cover with Carabiner (Black) Perfectly matches with Anker Soundcore Sport X10 Made of high quality soft silicone, scratch proof, shock proof and durable Carabiner is included to improve the practicality 360° all-round protection Easy to install',
  'image': 'https://m.media-amazon.com/images/I/31jUk+YZzeL._AC_.jpg',
  'rating_number': 112,
  'price': 10.5,
  'average_rating': 4.2,
  'parent_asin': 'B0B76GG8L1'},
 {'preprocessed_description': 'TP-Link TL-SM331T | 1000Base-T RJ45 SFP Module | 1.25G Copper SFP Transceiver | SFP to Ethernet | Plug and Play | Hot Pluggable | Up to 100m distance | | Durable Metal Casing | Versatile Compatibility 【SFP to RJ45 1000Base-T Copper SFP】Transmit data seamlessly up to 100 meters between your SFP interface and the copper gigabit port. 【Wide Compatibility】Compatible with most fiber switches, media converters, routers or other fiber optic equipments with SFP ports, TL-SM331T provides additional copper cable connections for peace of mind. 【Easy for deployment】Plug and Play with no software installation or configuration/technician needed. 【Durable Metal Casing】Ensures strength and reliability for a long time, maintaining a stable connection in a wide range of environments. 【Hot Pluggable】Plug in or remove your SFP module without needing to shutdown your network. Hot swap-ability ensures your network always stays up.',
  'image': 'https://m.media-amazon.com/images/I/31XzyYFo3xL._AC_.jpg',
  'rating_number': 104,
  'price': 23.99,
  'average_rating': 4.5,
  'parent_asin': 'B09RMJWBSM'},
 {'preprocessed_description': 'Fire HD 8 & HD 8 Plus Tablet Case for Kids (Only 12th Gen, 2022 Release) - DJ&RPPQ Lightweight Shockproof Cover with Handle Stand for Kindle Fire HD 8 Kids Tablet & Kids Pro Tablet - Blue Designed for Amazon All-New Kindle Fire HD 8 & Fire HD 8 Plus Tablet, Fire HD 8 Kids tablet & Fire HD 8 Kids Pro tablet (12th Generation 2022 Release), NOT fit for other models. Cutouts for clear access to all Amazon Kindle Fire HD 8 Plus / Fire HD 8 Tablet(12TH Generation, 2022Release) / Fire HD 8 Kids Pro 2022Tablet buttons, ports, speakers and rear-camera. Raised screen bezel edges for extra protection when fall. Kindle fire 8 case made with dense heavy duty EVA foam, Material can withstand considerable wear and tear and provide extreme shock protection.Super light weight and durable hazard free safe material perfect for kids and grownups alike. Built-in Kickstand- Designed with a foldable kick-stand on the back of the case, allows you to set up multiple angles and gives you the hands-free convenience when watching videos and movies. All-New Kindle Fire HD 8/8 plus Tablet case x 1.(The tablet is not included, and NO screen protector included); About customer service: Any questions please feel free to contact us and we will reply as soon as possible within 24 hours.',
  'image': 'https://m.media-amazon.com/images/I/512AWwRyqzL._AC_.jpg',
  'rating_number': 739,
  'price': 12.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BG6TMXDD'},
 {'preprocessed_description': 'Wekily Bluetooth 5.3 Headphones, Wireless Earbuds with 40H Playtimes Charge Case, Deep Bass, IPX7 Waterproof Running Earphones with 4-Mic Clear Call, LED Display, in Ear Headphones for Work/Gym Excellent Sound Quality: Wireless earbuds adopte graphene drivers and a polymer composite diaphragm carrying an AAC/SBC audio decoder, resulting in up to 43% bass enhancement. Audio technology is losslessly transmitted for a clearer stereo sound from the headphones. 40Hrs Cycle Playtimes: The 400mAh charging case has a playtime of 35 hours and the wireless headphones have a single playtime of 5hours of music. Quick charge in 10 minutes, 1 hour of use. In case of emergency. Bluetooth 5.3 Technology: The wireless headphones adopt bluetooth 5.3 chip, low battery consumption, fast transmission speed, and stable connection range up to 18m. Clear Call: Bluetooth earbuds adopt 4-microphone ENC reduction technology, combined with 13mm speakers, Making call is still very clear in public or gym environments. IPX7 Waterproof: Wireless sports earphones use nano-coating technology, waterproof and sweat-proof have passed the IPX7 standard, which is very suitable for your daily use.',
  'image': 'https://m.media-amazon.com/images/I/41qSQNF53EL._AC_.jpg',
  'rating_number': 2752,
  'price': 25.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BRV544MV'},
 {'preprocessed_description': "seenda Wired Mouse - USB Computer Mouse Wired with RGB Backlit Optical LED Mouse with Attached USB Cord for Laptops Notebooks Chromebook - Rose Gold Play in A Colorful Way -- A optical wired computer mouse featuring with rainbow colored changing light around the base of the mouse, you can choose how they are displayed as well as the ability to turn the colors off when you're not using it Plug & Play Wired Mouse -- Plug it to your computers and and it's been working ever since, with no issues or need to change settings. The smooth tracking, quiet, soft-touch buttons and wheels would be added features Sleek & Comfortable Shape -- This computer mouse does all that it needs in a comfortable shape and size, fits well for both small hands and big hands. It has a long enough cord to reach your computer easily Responsive & Accurate Click -- The optical response to the computer its very good, moving cursors, scrolling pages makes seamless efforts in using this mouse Universal Compatibility -- Works with Notebook, Computer, PC, Laptop,Chromebook with USB port, running on Windows XP/Vista/7/8/10 Mac OS X 10.4 etc.【Notice:This product is not compatible with macbook pro or other laptops which only have type c ports】",
  'image': 'https://m.media-amazon.com/images/I/41czXlj4jSS._AC_.jpg',
  'rating_number': 163,
  'price': 9.99,
  'average_rating': 4.5,
  'parent_asin': 'B0BYD7PGV1'},

Define the embedding function

In [16]:
response = openai.embeddings.create(
    input="Random text",
    model="text-embedding-3-small"
)

In [17]:
response

CreateEmbeddingResponse(data=[Embedding(embedding=[-0.0159454345703125, -0.0039520263671875, 0.00843048095703125, 0.0036773681640625, -0.042877197265625, -0.062744140625, -0.0078887939453125, 0.011993408203125, -0.013092041015625, -0.0061187744140625, -0.006755828857421875, 0.0118255615234375, -0.020721435546875, 0.03778076171875, 0.0284423828125, -0.0185699462890625, -0.03204345703125, -0.006649017333984375, -0.05047607421875, 0.033660888671875, -0.0155181884765625, 0.024322509765625, -0.02020263671875, 5.1975250244140625e-05, 0.0191650390625, -0.0015325546264648438, 0.0158843994140625, -0.00872039794921875, 0.03643798828125, -0.036376953125, 0.0244598388671875, -0.04296875, 0.0224609375, -0.0254364013671875, 0.01399993896484375, 0.00911712646484375, 0.050384521484375, 0.0001552104949951172, 0.0225372314453125, 0.0023021697998046875, -0.0031719207763671875, -0.04742431640625, 0.031585693359375, 0.0275115966796875, 0.03009033203125, 0.026275634765625, -0.0198516845703125, -0.007556915283203125, 0.0355224609375, 0.06158447265625, -0.04840087890625, 0.0267791748046875, 0.002315521240234375, 0.048187255859375, -0.00562286376953125, -0.018035888671875, -0.036834716796875, 0.044281005859375, -0.0181427001953125, -0.0218963623046875, 0.021209716796875, 0.0013637542724609375, -0.0189056396484375, 0.0244903564453125, 0.02978515625, 0.00396728515625, -0.0252532958984375, 0.035186767578125, 0.0169525146484375, 0.0426025390625, -0.0010251998901367188, -0.005443572998046875, -0.06646728515625, 0.0003075599670410156, -0.035400390625, 0.006305694580078125, 0.00616455078125, -0.01137542724609375, 0.0051727294921875, 0.0250701904296875, 0.04132080078125, 0.03912353515625, -0.02490234375, -0.0181427001953125, -0.06256103515625, -0.0021457672119140625, -0.108154296875, -0.007427215576171875, -0.004535675048828125, -0.023834228515625, -0.024688720703125, 0.0022563934326171875, -0.043243408203125, -0.00696563720703125, 0.0007853507995605469, 0.00408172607421875, 0.01409149169921875, 0.03466796875, 0.024810791015625, -0.0126495361328125, 0.014984130859375, -0.0367431640625, -0.01139068603515625, 0.0010423660278320312, -0.018707275390625, 0.006450653076171875, -0.00873565673828125, -0.033935546875, -0.0426025390625, 0.0182952880859375, -0.0638427734375, -0.0289306640625, 0.0187530517578125, -0.00566864013671875, -0.0169830322265625, -0.0276031494140625, 0.04364013671875, 0.0025615692138671875, 0.004058837890625, -0.0330810546875, -0.0026264190673828125, -0.00841522216796875, 0.019775390625, -0.0399169921875, -0.02996826171875, -0.03619384765625, -0.00710296630859375, -0.023712158203125, -0.00994110107421875, 0.0094146728515625, 0.04736328125, -0.032073974609375, -0.00720977783203125, -0.0110931396484375, -0.06463623046875, -0.004711151123046875, -0.00385284423828125, -0.00620269775390625, -0.0528564453125, 0.03228759765625, -0.013427734375, -0.013641357421875, -0.0014905929565429688, -0.020721435546875, -0.0015172958374023438, -0.02203369140625, -0.021026611328125, -0.01206207275390625, 0.01253509521484375, 0.00316619873046875, -0.04205322265625, 0.03997802734375, -0.05487060546875, 0.024810791015625, 0.04095458984375, -0.0280609130859375, 0.031494140625, 0.0164794921875, -0.03631591796875, -0.01885986328125, -0.01015472412109375, -0.019805908203125, 0.0057373046875, 0.00435638427734375, -0.02239990234375, -0.01158905029296875, 0.043701171875, -3.8623809814453125e-05, -0.08697509765625, 0.01123046875, -0.0046539306640625, -0.05303955078125, -0.05072021484375, 0.003017425537109375, -0.02191162109375, 0.0204010009765625, 0.01064300537109375, -0.01149749755859375, -0.007114410400390625, 0.063232421875, 0.038116455078125, 0.06341552734375, 0.0234375, -0.0015048980712890625, -0.004512786865234375, -0.052032470703125, 0.03570556640625, -0.005580902099609375, 0.003055572509765625, 0.0054931640625, -0.026397705078125, 0.0138702392578125, 0.0305023193359375, -0.0040283203125, -0.01459503173828125, -0.027130126953125, 0.054718017578125, 0.001529693603515625, -0.0135040283203125, 0.0089263916015625, 0.032379150390625, 0.0538330078125, -0.01116943359375, -0.01169586181640625, -0.046661376953125, -0.04791259765625, -0.0257720947265625, 0.013397216796875, -0.00586700439453125, -0.004558563232421875, 0.1148681640625, -0.0484619140625, -0.0269012451171875, -0.048919677734375, -0.05731201171875, -0.040924072265625, 0.040924072265625, 0.03594970703125, 0.00968170166015625, -0.0281829833984375, -0.01055908203125, 0.041839599609375, 0.06097412109375, 0.0225677490234375, 0.00024378299713134766, 0.01123809814453125, 0.058349609375, -0.0015363693237304688, 0.0004525184631347656, 0.0406494140625, 0.056610107421875, 0.00554656982421875, 0.017913818359375, -0.04144287109375, 0.059326171875, 0.028350830078125, 0.01302337646484375, 0.004856109619140625, 0.00353240966796875, 0.0305633544921875, -0.017486572265625, -0.01442718505859375, 0.037628173828125, 0.0265045166015625, 0.03765869140625, -0.0316162109375, -0.0190887451171875, -0.0364990234375, 0.045501708984375, 0.00251007080078125, 0.02825927734375, -0.0169525146484375, -0.017364501953125, -0.0039825439453125, 0.026702880859375, -0.03564453125, -0.0007448196411132812, 0.027618408203125, 0.0316162109375, -0.0333251953125, -0.044403076171875, -0.044189453125, -0.0670166015625, 0.0072174072265625, -0.005298614501953125, -0.02362060546875, 0.0302734375, -0.015106201171875, 0.0283966064453125, -0.059539794921875, -0.0142974853515625, -0.0179595947265625, 0.005626678466796875, 0.031158447265625, 0.0092926025390625, 0.044830322265625, -0.01690673828125, -0.0009098052978515625, -0.0262908935546875, 0.0276336669921875, -0.0210418701171875, 0.01125335693359375, -0.032440185546875, -0.0198974609375, -0.024261474609375, -0.011749267578125, 0.044036865234375, 0.005504608154296875, 0.02398681640625, 0.0003731250762939453, -0.01045989990234375, -0.017608642578125, 0.0421142578125, -0.0197601318359375, -0.00414276123046875, 0.0162811279296875, 0.0270538330078125, 0.024688720703125, -0.0065765380859375, 0.01309967041015625, 0.051666259765625, 0.00574493408203125, 0.0136871337890625, 0.025421142578125, -0.0225677490234375, 0.032745361328125, 0.003173828125, -0.01087188720703125, 0.0277099609375, -0.0150604248046875, 0.0010938644409179688, 0.033416748046875, -0.002452850341796875, -0.00927734375, -0.032928466796875, -0.03289794921875, 0.01331329345703125, 0.040313720703125, 0.058868408203125, -0.07818603515625, 0.074951171875, -0.054779052734375, 0.061737060546875, -0.0220489501953125, 0.007808685302734375, -0.0135498046875, 0.057769775390625, 0.030059814453125, 0.052154541015625, -0.01190948486328125, -0.01158905029296875, -0.03363037109375, 0.0321044921875, 0.0049896240234375, 0.051483154296875, -0.03936767578125, -0.01464080810546875, 0.032470703125, 0.053436279296875, 0.00024580955505371094, -0.0121612548828125, 0.01366424560546875, 0.0024280548095703125, -0.055572509765625, -0.009552001953125, -0.056793212890625, -0.007568359375, 0.004421234130859375, -0.0213775634765625, 0.01399993896484375, -0.00334930419921875, 0.021728515625, 0.017974853515625, -0.0657958984375, -0.00287628173828125, -0.0149688720703125, 0.020416259765625, 0.0248565673828125, 0.00946807861328125, 0.0154266357421875, 0.0186920166015625, 0.028289794921875, 0.0183258056640625, -0.0231475830078125, 0.03399658203125, 0.0177764892578125, -0.037750244140625, 0.01007843017578125, 0.0092315673828125, -0.0239410400390625, -0.035186767578125, 0.02886962890625, -0.020477294921875, 0.0013666152954101562, -0.028411865234375, 0.009735107421875, -0.0200653076171875, 0.03289794921875, 0.042144775390625, 0.037506103515625, -0.0287322998046875, 0.0260772705078125, -0.0308837890625, -0.0197601318359375, 0.035919189453125, 0.0215911865234375, 0.02838134765625, 0.010345458984375, -0.047332763671875, -0.00838470458984375, 0.0088043212890625, 0.0211639404296875, -0.0155181884765625, 0.0350341796875, -6.9141387939453125e-06, 0.01485443115234375, -0.00383758544921875, 0.0234222412109375, -0.02520751953125, -0.004241943359375, 0.05389404296875, -0.00435638427734375, -0.03924560546875, 0.0167083740234375, -0.0268096923828125, 0.0198822021484375, -0.025665283203125, 0.029022216796875, 0.0467529296875, 0.0078277587890625, 0.040435791015625, -0.014404296875, 0.034454345703125, 0.009185791015625, -0.014923095703125, 0.009613037109375, 0.077392578125, 0.006732940673828125, 0.0005645751953125, 0.05047607421875, -0.028900146484375, -0.0218505859375, -0.0377197265625, -0.0236663818359375, -0.01123809814453125, 0.0557861328125, 0.0504150390625, -0.038330078125, -0.0161895751953125, -0.0296783447265625, -0.000843048095703125, -0.023345947265625, -0.0161285400390625, -0.0036220550537109375, 0.02899169921875, -0.0107269287109375, -0.0198516845703125, 0.0309906005859375, -0.01175689697265625, -0.039031982421875, -0.014556884765625, 0.024169921875, -0.0706787109375, 0.0087127685546875, -0.027191162109375, 0.0188751220703125, 0.01739501953125, 0.0139007568359375, -0.035888671875, -0.045013427734375, -0.01275634765625, -0.0254974365234375, -0.006565093994140625, -0.040771484375, 0.033294677734375, -0.033477783203125, 0.039154052734375, 0.01355743408203125, -0.002239227294921875, 0.0261993408203125, 0.015594482421875, -0.029876708984375, -0.0286407470703125, 0.0010814666748046875, 0.0288848876953125, -0.0604248046875, -0.00720977783203125, 0.0428466796875, 0.0428466796875, -0.00640106201171875, -0.01546478271484375, 0.0120697021484375, 0.00826263427734375, 0.02545166015625, 0.0062103271484375, -0.02716064453125, 0.029541015625, -0.062255859375, -0.01113128662109375, 0.0244140625, 0.03216552734375, 0.003147125244140625, 0.013153076171875, 0.00238800048828125, -0.016998291015625, 0.0855712890625, -0.007602691650390625, 0.022369384765625, 0.01511383056640625, -0.0111236572265625, -0.03155517578125, 0.0201873779296875, 0.0298614501953125, -0.0194854736328125, 0.03143310546875, -0.031463623046875, -0.0146331787109375, -0.03228759765625, -0.01096343994140625, -0.06536865234375, -0.01190948486328125, 0.0036640167236328125, -0.0195465087890625, 0.0221710205078125, 0.026641845703125, 0.0194549560546875, 0.0127410888671875, 0.00298309326171875, 0.0030517578125, 0.0281982421875, 0.0165557861328125, 0.0003867149353027344, 0.0052642822265625, -0.016815185546875, -0.007663726806640625, 0.00899505615234375, -0.01383209228515625, -0.006771087646484375, -0.01055908203125, -0.04669189453125, 0.0323486328125, 0.0301055908203125, 0.01290130615234375, -0.01465606689453125, 0.005924224853515625, -0.051116943359375, -0.036041259765625, -0.023468017578125, -0.0028133392333984375, 0.008148193359375, 0.01050567626953125, 0.00847625732421875, 0.07513427734375, 0.01617431640625, -0.002834320068359375, -0.03717041015625, -0.0060577392578125, 0.00495147705078125, 0.03802490234375, 0.0055694580078125, 0.0124359130859375, 0.0411376953125, 0.042633056640625, -0.01259613037109375, -0.04559326171875, 0.0266265869140625, 0.014068603515625, -0.0036869049072265625, 0.0018167495727539062, -0.01081085205078125, 0.0205078125, -0.004634857177734375, -0.00168609619140625, -0.01776123046875, 0.0341796875, -0.00937652587890625, -0.0012540817260742188, 0.02386474609375, 0.032257080078125, 0.01367950439453125, 0.0103759765625, 0.00086212158203125, -0.0006103515625, 0.00737762451171875, -0.0159454345703125, 0.01033782958984375, -0.0250091552734375, 0.044586181640625, 0.03704833984375, -0.0283203125, 0.0200042724609375, 0.0172576904296875, 0.0033855438232421875, -0.031463623046875, -0.01067352294921875, -0.00251007080078125, 0.032501220703125, -0.005313873291015625, -0.025848388671875, 0.019134521484375, -0.007061004638671875, 0.03350830078125, 0.0284271240234375, 0.0276336669921875, -0.0491943359375, 0.034912109375, 0.00753021240234375, -0.01806640625, 0.003391265869140625, 0.0038909912109375, 0.04583740234375, 0.0242919921875, -0.0027217864990234375, 0.03607177734375, 0.0006160736083984375, 0.00984954833984375, -0.0147247314453125, -0.038055419921875, -0.03570556640625, -0.001506805419921875, 0.03363037109375, -0.00445556640625, -0.00522613525390625, -0.01517486572265625, 0.0213623046875, 0.0164642333984375, -0.00989532470703125, -0.01751708984375, 0.0147857666015625, -0.0439453125, -0.007205963134765625, 0.01422882080078125, 0.00676727294921875, -0.0157470703125, -0.0201568603515625, 0.00677490234375, -0.033111572265625, -0.01058197021484375, 0.00859832763671875, 0.017974853515625, -0.0296630859375, 0.0021152496337890625, 0.040374755859375, -0.00862884521484375, -0.039337158203125, 0.0024318695068359375, -0.01525115966796875, -0.0211334228515625, 0.01456451416015625, -0.00916290283203125, 0.006305694580078125, -0.0011348724365234375, -0.0005888938903808594, -0.0201568603515625, -0.00844573974609375, -0.0109710693359375, 0.0223236083984375, 0.009124755859375, 0.01175689697265625, -0.0256500244140625, 0.0316162109375, -0.009613037109375, 0.013885498046875, -0.0282745361328125, 0.044219970703125, -0.009124755859375, 0.02264404296875, 0.01580810546875, 0.01180267333984375, -0.038726806640625, -0.016510009765625, -0.0025501251220703125, 0.004970550537109375, -0.01483917236328125, -0.0086517333984375, -0.022003173828125, -0.00592041015625, -0.023468017578125, -0.004444122314453125, -0.028045654296875, -0.006862640380859375, -0.0191497802734375, -0.015289306640625, -0.0072174072265625, -0.03692626953125, 0.045318603515625, -0.0287628173828125, -0.026947021484375, -0.01447296142578125, 0.023895263671875, 0.0011034011840820312, 0.031463623046875, -0.0011034011840820312, -0.008087158203125, 0.0212249755859375, 0.01384735107421875, 0.00493621826171875, -0.04595947265625, 0.0105438232421875, -0.00849151611328125, 0.0142364501953125, 0.010589599609375, -0.020294189453125, -0.01666259765625, -0.0238189697265625, 0.03387451171875, 0.026275634765625, 0.018280029296875, -0.0328369140625, -0.015045166015625, -0.04559326171875, -0.0263824462890625, 0.04644775390625, 0.0228424072265625, 0.0205841064453125, -0.00948333740234375, 0.0060882568359375, 0.02557373046875, -0.0296630859375, -0.03704833984375, 0.012481689453125, 0.017974853515625, -0.0210113525390625, 0.0150604248046875, 0.0156707763671875, -0.041046142578125, 0.0214080810546875, -0.02166748046875, 0.0217437744140625, 0.0009007453918457031, 0.00047206878662109375, -0.00865936279296875, -0.01325225830078125, -0.0027618408203125, -0.0231170654296875, 0.01806640625, 0.0091094970703125, -0.026336669921875, -0.00855255126953125, -0.005641937255859375, 0.011077880859375, 0.03314208984375, 0.0149688720703125, -0.0158843994140625, -0.0232086181640625, -0.03472900390625, 0.02593994140625, -0.033111572265625, -0.003009796142578125, 0.05224609375, 0.00682830810546875, 0.01142120361328125, 0.044281005859375, -0.020416259765625, 0.0011653900146484375, -0.0018310546875, -0.01153564453125, -0.0177001953125, 0.0016269683837890625, -0.00489044189453125, 0.0002956390380859375, -0.004852294921875, 0.006542205810546875, 0.0253143310546875, -0.010589599609375, 0.01403045654296875, 0.037017822265625, -0.0003662109375, -0.0106353759765625, -0.00334930419921875, -0.0494384765625, 0.01425933837890625, -0.021759033203125, -0.0173187255859375, -0.00975799560546875, -0.034698486328125, 0.042022705078125, 0.0010099411010742188, 0.01439666748046875, 0.07330322265625, -0.0032501220703125, 0.042449951171875, -0.0026760101318359375, 0.036468505859375, -0.043487548828125, -0.025604248046875, -0.00817108154296875, 0.005390167236328125, -0.01438140869140625, 0.01351165771484375, 0.01314544677734375, -0.007717132568359375, -0.015411376953125, 0.01007843017578125, 0.01276397705078125, -0.0170440673828125, -0.05841064453125, 0.039703369140625, -0.00569915771484375, -0.023956298828125, -0.0077362060546875, 0.016448974609375, -0.0328369140625, 0.0215301513671875, -0.00830078125, -0.0164337158203125, 0.036834716796875, 0.01522064208984375, 0.005779266357421875, -0.004138946533203125, 0.00820159912109375, -0.058502197265625, 0.0309600830078125, -0.0244598388671875, -0.02496337890625, 0.015777587890625, -0.00656890869140625, -0.080078125, 0.0181121826171875, -0.002674102783203125, 0.0214385986328125, -0.0053253173828125, 0.001972198486328125, 0.04010009765625, 0.0302581787109375, -0.005435943603515625, -0.0246734619140625, 0.039276123046875, -0.020172119140625, -0.0200347900390625, -0.004421234130859375, 0.01348114013671875, -0.01152801513671875, 0.01277923583984375, -0.021942138671875, -0.040557861328125, -0.0227203369140625, -0.0282135009765625, -0.007686614990234375, 0.035919189453125, -0.01360321044921875, -0.022186279296875, -0.01058197021484375, -0.0059356689453125, 0.0308685302734375, 0.006572723388671875, -0.01456451416015625, 0.047393798828125, 0.003726959228515625, 0.0176239013671875, -0.019012451171875, -0.0008068084716796875, -0.0421142578125, -0.01348876953125, 0.00011795759201049805, 0.024200439453125, -0.01568603515625, -0.016937255859375, -0.035980224609375, -0.002895355224609375, 0.0293426513671875, -0.016754150390625, 0.004337310791015625, 0.0027141571044921875, 0.003810882568359375, -0.034271240234375, -0.02105712890625, -0.0017843246459960938, -0.0003733634948730469, 0.041778564453125, -0.0242462158203125, -0.012359619140625, 0.046478271484375, -0.053131103515625, -0.004787445068359375, -0.0098876953125, -0.00278472900390625, 0.016693115234375, -0.001644134521484375, 0.00032520294189453125, 0.017669677734375, 0.023162841796875, -0.031707763671875, -0.0069732666015625, 0.023345947265625, 0.031402587890625, -0.00445556640625, -0.0215301513671875, 0.028533935546875, -0.01134490966796875, 0.02239990234375, 0.00677490234375, -0.0408935546875, 0.03936767578125, 0.016571044921875, 0.021820068359375, -0.042266845703125, 0.042022705078125, -0.0030803680419921875, -0.00821685791015625, 0.0123138427734375, 0.00146484375, -0.01450347900390625, 0.028839111328125, -0.012603759765625, -0.046295166015625, 0.00980377197265625, 0.0494384765625, -0.005779266357421875, -0.0030803680419921875, -0.01221466064453125, -0.008575439453125, -0.019012451171875, -0.0103912353515625, 0.01552581787109375, -0.0009579658508300781, -0.01654052734375, 0.02386474609375, -0.031951904296875, -0.03631591796875, -0.0270843505859375, -0.0227508544921875, 0.037200927734375, -0.0203704833984375, 0.0523681640625, 0.0209503173828125, -0.051116943359375, 0.027984619140625, 0.0181732177734375, 0.0224761962890625, 0.0283203125, -0.00821685791015625, 0.0282745361328125, 0.022125244140625, -0.00940704345703125, -0.0003292560577392578, -0.02935791015625, -0.0199737548828125, 0.01169586181640625, 0.0101165771484375, -0.0277862548828125, -0.0467529296875, -0.018096923828125, -0.0171661376953125, 0.01268768310546875, 0.023193359375, -0.00042557716369628906, 0.0279541015625, 0.0040283203125, -0.00133514404296875, 0.004131317138671875, -0.007015228271484375, -0.0355224609375, 0.006488800048828125, 0.047515869140625, -0.00980377197265625, 0.03680419921875, -0.0037364959716796875, 0.0028629302978515625, 0.0233306884765625, -0.0193328857421875, 0.0106048583984375, -0.02301025390625, 0.007617950439453125, 0.0188446044921875, -0.01001739501953125, 0.00197601318359375, 0.0174560546875, -0.02056884765625, -0.007110595703125, -0.01132965087890625, -0.0282745361328125, 0.0165863037109375, -0.03192138671875, 0.013092041015625, -0.0233917236328125, 0.057159423828125, -0.013519287109375, 0.0294036865234375, 0.016204833984375, -0.002178192138671875, 0.03228759765625, -0.004634857177734375, -0.038116455078125, 0.01340484619140625, -0.026275634765625, -0.0024967193603515625, -0.01385498046875, 0.002079010009765625, 0.01523590087890625, 0.0009369850158691406, 0.00803375244140625, 0.0177001953125, 0.010101318359375, -0.03448486328125, 0.0311431884765625, 0.024810791015625, 0.0178985595703125, 0.0171661376953125, -0.04534912109375, 0.039398193359375, 0.02081298828125, 0.007709503173828125, -0.0232696533203125, 0.0361328125, -0.0309295654296875, 0.053009033203125, -0.002960205078125, 0.004970550537109375, 0.0040283203125, -0.006031036376953125, 0.00939178466796875, -0.025390625, 0.0281982421875, 0.0

In [18]:
len(response.data[0].embedding)

1536

In [25]:
def get_embedding(text,model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [26]:
get_embedding("Hi.")

[0.01244354248046875,
 -0.0029582977294921875,
 0.0164947509765625,
 0.007389068603515625,
 -0.01091766357421875,
 -0.00948333740234375,
 -0.033172607421875,
 0.04443359375,
 -0.01084136962890625,
 -0.048187255859375,
 -0.0018243789672851562,
 -0.033538818359375,
 -0.0014133453369140625,
 -0.027069091796875,
 0.034515380859375,
 0.027069091796875,
 -0.04180908203125,
 0.03704833984375,
 -0.034515380859375,
 0.057281494140625,
 0.05670166015625,
 0.015838623046875,
 -0.001789093017578125,
 0.016815185546875,
 0.002819061279296875,
 0.0049896240234375,
 0.0784912109375,
 -0.0032196044921875,
 0.0020618438720703125,
 -0.006679534912109375,
 0.03338623046875,
 -0.0382080078125,
 -0.0112457275390625,
 -0.0180206298828125,
 -0.00041365623474121094,
 -0.005603790283203125,
 -0.0195770263671875,
 0.0303802490234375,
 0.01499176025390625,
 -0.04833984375,
 0.032501220703125,
 -0.01004791259765625,
 -0.006053924560546875,
 0.0206146240234375,
 0.0013942718505859375,
 0.005702972412109375,
 -0.04345703125,
 -0.01375579833984375,
 0.0491943359375,
 0.0066375732421875,
 -0.03717041015625,
 0.03125,
 0.03985595703125,
 0.1007080078125,
 0.0303497314453125,
 -0.021331787109375,
 0.050048828125,
 0.039398193359375,
 -0.031402587890625,
 0.03363037109375,
 0.01141357421875,
 -0.029632568359375,
 0.03466796875,
 0.046051025390625,
 0.00568389892578125,
 0.0272369384765625,
 -0.005687713623046875,
 0.01432037353515625,
 -0.043212890625,
 -0.00628662109375,
 -0.015838623046875,
 -0.004730224609375,
 0.0220794677734375,
 0.005756378173828125,
 -0.0009560585021972656,
 -0.036376953125,
 -0.00667572021484375,
 -0.028045654296875,
 0.01166534423828125,
 -0.0196533203125,
 -0.034942626953125,
 0.00470733642578125,
 -0.039703369140625,
 -0.0341796875,
 -0.035491943359375,
 -0.01494598388671875,
 -0.046905517578125,
 0.002216339111328125,
 0.0032444000244140625,
 -0.0111236572265625,
 -0.04229736328125,
 0.048065185546875,
 -0.02142333984375,
 0.024139404296875,
 -0.0158843994140625,
 -0.029632568359375,
 -0.0176849365234375,
 0.00832366943359375,
 0.0232086181640625,
 -0.00763702392578125,
 0.035400390625,
 -0.0181427001953125,
 -0.0104522705078125,
 0.030426025390625,
 0.0295867919921875,
 -0.0216827392578125,
 0.02484130859375,
 -0.016571044921875,
 -0.05364990234375,
 0.004642486572265625,
 -0.08599853515625,
 -0.05950927734375,
 -0.0034694671630859375,
 -0.04290771484375,
 0.00403594970703125,
 -0.002960205078125,
 0.0017957687377929688,
 -0.040191650390625,
 0.01369476318359375,
 -0.0753173828125,
 0.00788116455078125,
 -0.020843505859375,
 0.04010009765625,
 -0.036834716796875,
 -0.055084228515625,
 -0.003936767578125,
 0.0004088878631591797,
 0.052520751953125,
 -0.0176849365234375,
 -0.0143585205078125,
 0.0718994140625,
 -0.0029582977294921875,
 0.016326904296875,
 -0.022857666015625,
 -0.033355712890625,
 -0.033050537109375,
 -0.02178955078125,
 0.036041259765625,
 -0.041473388671875,
 0.00763702392578125,
 0.0548095703125,
 -0.031341552734375,
 -0.0030994415283203125,
 0.0249786376953125,
 0.032135009765625,
 -0.0156707763671875,
 0.01010894775390625,
 0.033203125,
 -0.04119873046875,
 -0.01021575927734375,
 0.013824462890625,
 0.007663726806640625,
 -0.05499267578125,
 -0.004283905029296875,
 0.0172576904296875,
 -0.045257568359375,
 0.046722412109375,
 -0.033294677734375,
 -0.022064208984375,
 0.04901123046875,
 0.051971435546875,
 0.0028591156005859375,
 -0.005733489990234375,
 -0.0130462646484375,
 -0.033477783203125,
 0.0360107421875,
 -0.00650787353515625,
 0.045135498046875,
 -0.052001953125,
 0.005523681640625,
 0.0036830902099609375,
 0.034881591796875,
 -0.041168212890625,
 0.001995086669921875,
 -0.0247039794921875,
 0.0166778564453125,
 0.056182861328125,
 -0.018707275390625,
 -0.037353515625,
 0.00942230224609375,
 0.0224609375,
 0.05322265625,
 -0.0087890625,
 -0.01032257080078125,
 -0.0307464599609375,
 -0.0089569091796875,
 -0.0572509765625,
 -0.01152801513671875,
 -0.01476287841796875,
 0.0173492431640625,
 0.0049591064453125,
 0.07879638671875,
 -0.03564453125,
 0.004535675048828125,
 -0.0125579833984375,
 -0.0667724609375,
 0.0675048828125,
 0.004398345947265625,
 -0.04736328125,
 0.0037860870361328125,
 0.0182342529296875,
 -0.0178375244140625,
 0.0148773193359375,
 -0.007656097412109375,
 -0.0095062255859375,
 0.0036525726318359375,
 -0.03533935546875,
 0.047454833984375,
 0.014678955078125,
 -0.05511474609375,
 0.0718994140625,
 0.010833740234375,
 0.006198883056640625,
 0.0103302001953125,
 -0.0251617431640625,
 -0.039154052734375,
 0.050689697265625,
 0.0283660888671875,
 0.03131103515625,
 0.0008411407470703125,
 -0.03863525390625,
 0.0430908203125,
 0.079345703125,
 0.01534271240234375,
 0.04718017578125,
 0.04443359375,
 0.01861572265625,
 -0.004497528076171875,
 0.0127410888671875,
 0.0024738311767578125,
 -0.02783203125,
 0.046142578125,
 0.0083465576171875,
 -0.04522705078125,
 0.0034847259521484375,
 0.00957489013671875,
 -0.0101165771484375,
 -0.004917144775390625,
 0.01320648193359375,
 -0.015594482421875,
 -0.0130615234375,
 0.005916595458984375,
 0.0213470458984375,
 0.04669189453125,
 0.0276947021484375,
 -0.01248931884765625,
 0.01216888427734375,
 -0.0313720703125,
 0.005146026611328125,
 0.047760009765625,
 0.0006055831909179688,
 0.0196075439453125,
 0.002017974853515625,
 -0.035980224609375,
 -0.0231781005859375,
 -0.0025177001953125,
 0.0116119384765625,
 0.040008544921875,
 -0.02569580078125,
 -0.034912109375,
 -0.028472900390625,
 -0.041534423828125,
 -0.01052093505859375,
 -0.04339599609375,
 -0.032073974609375,
 -0.042236328125,
 0.02008056640625,
 0.0106964111328125,
 -0.0455322265625,
 -0.0114593505859375,
 0.002532958984375,
 -0.00511932373046875,
 0.037811279296875,
 0.033233642578125,
 -0.00946044921875,
 0.01181793212890625,
 0.0061492919921875,
 -0.03277587890625,
 0.0181884765625,
 0.0068817138671875,
 -0.0268096923828125,
 -0.00879669189453125,
 -0.002651214599609375,
 0.0248870849609375,
 -0.04461669921875,
 0.018035888671875,
 0.01148223876953125,
 -0.0256195068359375,
 0.0234375,
 0.035186767578125,
 0.0174560546875,
 -0.017547607421875,
 -0.01343536376953125,
 -0.039031982421875,
 0.0193328857421875,
 -0.006206512451171875,
 0.031707763671875,
 -0.056793212890625,
 0.01102447509765625,
 0.01995849609375,
 0.01611328125,
 -0.007389068603515625,
 0.0014238357543945312,
 0.0249786376953125,
 -0.0173797607421875,
 0.006214141845703125,
 0.01885986328125,
 0.022308349609375,
 -0.0021533966064453125,
 -0.003665924072265625,
 0.01381683349609375,
 0.016326904296875,
 0.0716552734375,
 -0.05804443359375,
 0.00853729248046875,
 -0.01334381103515625,
 0.012298583984375,
 0.0024776458740234375,
 0.0217742919921875,
 -0.0150146484375,
 0.01143646240234375,
 -0.00965118408203125,
 -0.002437591552734375,
 -0.0225372314453125,
 -0.046844482421875,
 0.0093841552734375,
 0.049072265625,
 0.0423583984375,
 0.0301513671875,
 0.0200958251953125,
 -0.00556182861328125,
 -0.01110076904296875,
 -0.01409149169921875,
 -0.005214691162109375,
 0.01007843017578125,
 0.01043701171875,
 -0.056060791015625,
 0.0426025390625,
 0.0158538818359375,
 0.04022216796875,
 -0.0394287109375,
 -0.034698486328125,
 -0.0302886962890625,
 -0.024078369140625,
 0.01366424560546875,
 -0.03521728515625,
 -0.00553131103515625,
 -0.033111572265625,
 -0.03143310546875,
 -0.01055908203125,
 0.016876220703125,
 0.029693603515625,
 -0.00896453857421875,
 -0.0170440673828125,
 -0.0192413330078125,
 0.007221221923828125,
 0.07733154296875,
 -0.0303802490234375,
 -0.058074951171875,
 0.0096282958984375,
 -0.038055419921875,
 0.0455322265625,
 0.00653076171875,
 -0.05224609375,
 0.01432037353515625,
 0.020050048828125,
 -0.06695556640625,
 -0.0028820037841796875,
 0.0220947265625,
 0.038787841796875,
 0.01432037353515625,
 -0.00534820556640625,
 0.01100921630859375,
 0.040740966796875,
 -0.04547119140625,
 0.04931640625,
 -0.00637054443359375,
 0.00025963783264160156,
 0.039154052734375,
 -0.0180206298828125,
 0.08294677734375,
 0.025726318359375,
 0.0218658447265625,
 0.0015401840209960938,
 0.032989501953125,
 -0.0209197998046875,
 0.03558349609375,
 -0.0089874267578125,
 0.003376007080078125,
 0.0182037353515625,
 0.05938720703125,
 0.0003256797790527344,
 0.0660400390625,
 -0.0196990966796875,
 0.005462646484375,
 -0.03302001953125,
 0.038360595703125,
 0.00940704345703125,
 -0.037933349609375,
 -0.026214599609375,
 0.02362060546875,
 -0.022918701171875,
 -0.044708251953125,
 0.0005464553833007812,
 0.009735107421875,
 0.005954742431640625,
 -0.02593994140625,
 0.01036834716796875,
 0.031890869140625,
 -0.050201416015625,
 0.0394287109375,
 -0.05181884765625,
 0.029327392578125,
 -0.006824493408203125,
 0.01361846923828125,
 -0.0216217041015625,
 -0.0067901611328125,
 0.007465362548828125,
 0.0218658447265625,
 -0.0239105224609375,
 0.006732940673828125,
 0.03350830078125,
 0.0498046875,
 0.026702880859375,
 -0.034912109375,
 0.0214080810546875,
 0.035430908203125,
 -0.00951385498046875,
 0.035247802734375,
 -0.069580078125,
 -0.01029205322265625,
 0.00524139404296875,
 -0.0261077880859375,
 0.009185791015625,
 -0.01041412353515625,
 0.008331298828125,
 0.0047149658203125,
 0.032745361328125,
 0.045562744140625,
 0.0007352828979492188,
 0.0101470947265625,
 0.0047149658203125,
 -0.00116729736328125,
 -0.0209503173828125,
 -0.007183074951171875,
 -0.0579833984375,
 0.0260772705078125,
 -0.0008616447448730469,
 -0.05181884765625,
 0.01053619384765625,
 -0.0207672119140625,
 0.0225677490234375,
 0.0025615692138671875,
 0.024566650390625,
 -0.004978179931640625,
 0.034881591796875,
 0.004734039306640625,
 0.005809783935546875,
 -0.007274627685546875,
 -0.0275421142578125,
 0.00656890869140625,
 0.0699462890625,
 0.0221099853515625,
 0.042572021484375,
 -0.01531219482421875,
 -0.020965576171875,
 0.00803375244140625,
 -0.00701141357421875,
 -0.0251617431640625,
 -0.03375244140625,
 -0.0047760009765625,
 0.012115478515625,
 0.0272216796875,
 -0.0250701904296875,
 0.0189208984375,
 -0.01346588134765625,
 -0.0179901123046875,
 0.010009765625,
 -0.0086669921875,
 -0.0205230712890625,
 0.00390625,
 0.0278472900390625,
 -0.00872802734375,
 0.03057861328125,
 0.01177978515625,
 0.037384033203125,
 -0.014617919921875,
 0.022064208984375,
 -0.0230255126953125,
 0.0024471282958984375,
 0.023834228515625,
 0.060760498046875,
 0.0611572265625,
 -0.015716552734375,
 -0.0268402099609375,
 -0.0391845703125,
 -0.025177001953125,
 -0.0626220703125,
 -0.018768310546875,
 -0.046661376953125,
 -0.032958984375,
 -0.03289794921875,
 0.0220794677734375,
 0.0367431640625,
 0.054473876953125,
 -0.0234222412109375,
 -0.0069580078125,
 0.007564544677734375,
 -0.01030731201171875,
 0.0169830322265625,
 -0.0031528472900390625,
 -0.01325225830078125,
 -0.01483154296875,
 -0.042388916015625,
 -0.03607177734375,
 0.0005574226379394531,
 -0.00997161865234375,
 0.0211639404296875,
 -0.0246734619140625,
 -0.060302734375,
 0.0465087890625,
 0.047515869140625,
 0.01471710205078125,
 -0.0112457275390625,
 -0.0335693359375,
 -0.00970458984375,
 -0.013427734375,
 0.0031948089599609375,
 -0.003597259521484375,
 0.0250091552734375,
 0.0011739730834960938,
 -0.00920867919921875,
 -0.02484130859375,
 0.029998779296875,
 -0.0263214111328125,
 -0.004993438720703125,
 0.032806396484375,
 -0.0146484375,
 0.01421356201171875,
 -0.0226593017578125,
 0.0174102783203125,
 0.01092529296875,
 -0.005218505859375,
 0.010650634765625,
 0.0016412734985351562,
 0.03436279296875,
 0.01250457763671875,
 -0.00463104248046875,
 0.0236053466796875,
 0.022491455078125,
 -0.0139923095703125,
 -0.0084228515625,
 0.03216552734375,
 0.04144287109375,
 0.0303497314453125,
 -0.035003662109375,
 -0.0270233154296875,
 -0.0232696533203125,
 0.007747650146484375,
 0.04180908203125,
 -0.018951416015625,
 -0.0131988525390625,
 -0.01258087158203125,
 -0.0008006095886230469,
 -0.0033359527587890625,
 0.05010986328125,
 0.01422119140625,
 0.002475738525390625,
 -0.0144500732421875,
 0.00397491455078125,
 -0.04595947265625,
 0.00749969482421875,
 -0.033660888671875,
 -0.07830810546875,
 -0.005886077880859375,
 -0.00632476806640625,
 0.01904296875,
 0.046600341796875,
 -0.004451751708984375,
 0.00555419921875,
 -0.0183868408203125,
 -0.04571533203125,
 0.0120086669921875,
 -0.020538330078125,
 -0.0367431640625,
 0.022705078125,
 0.0017156600952148438,
 -0.003131866455078125,
 0.04681396484375,
 0.010406494140625,
 0.040130615234375,
 -0.0022830963134765625,
 0.00649261474609375,
 0.0033855438232421875,
 0.02362060546875,
 -0.037689208984375,
 -0.0261993408203125,
 -0.0426025390625,
 -0.0291595458984375,
 0.023712158203125,
 0.016143798828125,
 -0.0009822845458984375,
 -0.01071929931640625,
 -0.0298309326171875,
 0.00389862060546875,
 0.02862548828125,
 -0.01361846923828125,
 -0.0075225830078125,
 0.0294342041015625,
 -0.00600433349609375,
 0.0108184814453125,
 0.00930023193359375,
 0.0028705596923828125,
 -0.0341796875,
 -0.037078857421875,
 0.0177459716796875,
 -0.0264434814453125,
 0.0153961181640625,
 -0.0023517608642578125,
 -0.01531219482421875,
 -0.0160064697265625,
 -0.033721923828125,
 0.01094818115234375,
 0.058319091796875,
 0.03997802734375,
 0.0499267578125,
 -0.02923583984375,
 -0.0238800048828125,
 0.00011742115020751953,
 0.0179901123046875,
 0.003658294677734375,
 -0.007183074951171875,
 0.03680419921875,
 0.0270538330078125,
 -0.041839599609375,
 -0.006343841552734375,
 -0.025360107421875,
 -0.01105499267578125,
 0.033355712890625,
 -0.051483154296875,
 0.01146697998046875,
 0.04705810546875,
 -0.0125579833984375,
 -0.021331787109375,
 0.059844970703125,
 -0.00017261505126953125,
 0.005252838134765625,
 0.0421142578125,
 -0.011749267578125,
 -0.0074462890625,
 0.0301971435546875,
 -0.037628173828125,
 -0.0171051025390625,
 -0.02825927734375,
 -0.019195556640625,
 -0.035919189453125,
 -0.0262603759765625,
 0.0035400390625,
 -0.0191802978515625,
 0.024261474609375,
 0.006290435791015625,
 0.0239105224609375,
 -0.006572723388671875,
 -0.020294189453125,
 -8.100271224975586e-05,
 0.0247802734375,
 0.038665771484375,
 0.0132293701171875,
 0.0032367706298828125,
 0.00679779052734375,
 0.047149658203125,
 -0.01398468017578125,
 0.0221405029296875,
 -0.0264434814453125,
 0.032562255859375,
 0.02587890625,
 0.03228759765625,
 -0.007129669189453125,
 -0.016082763671875,
 -0.0012884140014648438,
 -0.020538330078125,
 -0.026123046875,
 -0.0191192626953125,
 -0.0163421630859375,
 0.01605224609375,
 0.031494140625,
 0.05853271484375,
 0.006671905517578125,
 -0.01111602783203125,
 0.0239715576171875,
 -0.0003032684326171875,
 0.0276641845703125,
 0.01434326171875,
 0.001003265380859375,
 -0.0026569366455078125,
 -0.013671875,
 0.043060302734375,
 -0.002437591552734375,
 0.0257415771484375,
 0.00853729248046875,
 -0.00861358642578125,
 -0.026519775390625,
 -0.01386260986328125,
 0.0152130126953125,
 0.017242431640625,
 0.007785797119140625,
 -0.032562255859375,
 0.0160980224609375,
 0.02581787109375,
 0.02978515625,
 -0.0240325927734375,
 0.037384033203125,
 -0.0369873046875,
 -0.0243072509765625,
 -0.0011568069458007812,
 0.00753021240234375,
 -0.005527496337890625,
 -0.0377197265625,
 0.0227813720703125,
 -0.0318603515625,
 -0.0022182464599609375,
 -0.005733489990234375,
 0.007678985595703125,
 -0.0005521774291992188,
 -0.0215911865234375,
 -0.0280609130859375,
 -0.0009579658508300781,
 -0.0207366943359375,
 0.01494598388671875,
 0.00984954833984375,
 0.0169677734375,
 0.015716552734375,
 0.005889892578125,
 0.0141143798828125,
 0.033111572265625,
 -0.0149993896484375,
 -0.0265045166015625,
 -0.032928466796875,
 0.007450103759765625,
 -0.05218505859375,
 -0.029693603515625,
 0.0257568359375,
 0.04449462890625,
 0.0299224853515625,
 0.00922393798828125,
 0.004032135009765625,
 0.0117645263671875,
 0.040985107421875,
 -0.0130615234375,
 -0.020965576171875,
 0.0212249755859375,
 0.00977325439453125,
 0.001827239990234375,
 0.0421142578125,
 0.0158843994140625,
 -0.043792724609375,
 0.0239410400390625,
 0.001285552978515625,
 0.0184173583984375,
 0.00977325439453125,
 0.007480621337890625,
 0.054473876953125,
 -0.0078277587890625,
 -0.0112152099609375,
 0.0005717277526855469,
 0.013946533203125,
 -0.050872802734375,
 0.004550933837890625,
 -0.0255126953125,
 0.01519775390625,
 0.040252685546875,
 -0.027618408203125,
 -0.0043792724609375,
 -0.020172119140625,
 0.0291290283203125,
 -0.0005402565002441406,
 -0.046112060546875,
 0.005153656005859375,
 -0.0152130126953125,
 -0.003814697265625,
 -0.0126190185546875,
 0.01406097412109375,
 -0.00994873046875,
 0.0003216266632080078,
 -0.0045166015625,
 -0.0033512115478515625,
 -0.0037899017333984375,
 0.00507354736328125,
 0.0002868175506591797,
 -0.00783538818359375,
 -0.0112457275390625,
 -0.048431396484375,
 0.0026874542236328125,
 -0.00662994384765625,
 0.03045654296875,
 0.03472900390625,
 -2.5928020477294922e-05,
 0.009490966796875,
 0.0159149169921875,
 0.007167816162109375,
 -0.0182342529296875,
 -0.022796630859375,
 0.01557159423828125,
 0.0240478515625,
 0.0046539306640625,
 -0.01654052734375,
 -0.044036865234375,
 -0.012481689453125,
 -0.0014104843139648438,
 -0.01070404052734375,
 0.0090484619140625,
 0.0160675048828125,
 -0.0018367767333984375,
 -0.00838470458984375,
 0.05377197265625,
 -0.0081634521484375,
 0.0020580291748046875,
 -0.0169525146484375,
 0.0234527587890625,
 -0.0224456787109375,
 0.0361328125,
 0.0234375,
 0.0129852294921875,
 -0.0032196044921875,
 0.007404327392578125,
 0.0272064208984375,
 0.005107879638671875,
 0.00848388671875,
 0.0175628662109375,
 -0.039093017578125,
 0.01081085205078125,
 -0.0214080810546875,
 0.0007100105285644531,
 -0.03607177734375,
 0.0159149169921875,
 0.038604736328125,
 0.0007586479187011719,
 0.004505157470703125,
 -0.003910064697265625,
 0.0037078857421875,
 0.035308837890625,
 0.0229034423828125,
 -0.033294677734375,
 -0.0158843994140625,
 0.01476287841796875,
 0.028900146484375,
 -0.0216827392578125,
 -0.01065826416015625,
 -0.00679779052734375,
 0.01158905029296875,
 -0.025146484375,
 0.003803253173828125,
 0.036773681640625,
 -0.004116058349609375,
 0.00595855712890625,
 0.0177154541015625,
 -0.017791748046875,
 -0.033477783203125,
 0.01403045654296875,
 -0.005893707275390625,
 -0.0025196075439453125,
 0.041595458984375,
 0.0034275054931640625,
 -0.0121002197265625,
 0.0223541259765625,
 -0.0411376953125,
 -0.003162384033203125,
 -0.010162353515625,
 0.004497528076171875,
 0.00714874267578125,
 -0.0014429092407226562,
 0.031158447265625,
 -0.04022216796875,
 -0.01995849609375,
 0.0121612548828125,
 0.050384521484375,
 -0.0143585205078125,
 0.00911712646484375,
 -0.017608642578125,
 0.01873779296875,
 0.02496337890625,
 0.019805908203125,
 -0.01210784912109375,
 0.028167724609375,
 0.0015745162963867188,
 0.0177764892578125,
 0.020355224609375,
 0.00901031494140625,
 -0.0255889892578125,
 0.0209197998046875,
 0.004352569580078125,
 -0.0177154541015625,
 -0.00734710693359375,
 -0.00579833984375,
 0.001422882080078125,
 -0.0183563232421875,
 0.01288604736328125,
 0.00634002685546875,
 0.01593017578125,
 0.002712249755859375,
 -0.01186370849609375,
 -0.0078582763671875,
 -0.0379638671875,
 0.002056121826171875,
 -0.00794219970703125,
 0.004261016845703125,
 0.01386260986328125,
 -0.00417327880859375,
 0.0163116455078125,
 0.01177978515625,
 -0.0196685791015625,
 -0.04052734375,
 0.0184173583984375,
 0.0089569091796875,
 -0.031585693359375,
 0.0284576416015625,
 0.0006580352783203125,
 0.002521514892578125,
 0.0233001708984375,
 0.018646240234375,
 -0.0037364959716796875,
 -0.0294189453125,
 0.007068634033203125,
 0.02044677734375,
 -0.00205230712890625,
 0.002376556396484375,
 -0.01334381103515625,
 0.0191802978515625,
 -0.004238128662109375,
 -0.00479888916015625,
 0.0114593505859375,
 0.0183258056640625,
 -0.006099700927734375,
 0.0157470703125,
 0.03570556640625,
 -0.001422882080078125,
 -0.005401611328125,
 0.01152801513671875,
 0.0129547119140625,
 -0.03533935546875,
 0.027496337890625,
 -0.00899505615234375,
 0.0369873046875,
 0.01079559326171875,
 0.032470703125,
 0.0303802490234375,

Create Qdrant Collection

In [27]:
qdrant_client = QdrantClient(url="http://localhost:6334")

/Users/gaurisharma/developer/ai-engineering-bootcamp/cohort_5/ai-engineering-bootcamp-amazon-assistant/.venv/lib/python3.12/site-packages/qdrant_client/qdrant_remote.py:295: UserWarning: Failed to obtain server version. Unable to check client-server compatibility. Set check_compatibility=False to skip version check.
  show_warning(

In [28]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-01",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
    on_disk_payload=True
)
qdrant_client.get_collection("Amazon-items-collection-01")

ResponseHandlingException: illegal request line